// English Quest question engine
// Generates 3,500 structured questions: 500 per grade (6-12).
const WORLDS={6:'Green Valley',7:'Crystal Forest',8:'Mystic Kingdom',9:'Dragon Valley',10:'Ancient Academy',11:'Shadow Empire',12:'Final Kingdom'};
const TOPICS={6:['Family','School','Friends','Animals','Food','Daily activities','Hobbies','Places'],7:['Health','Environment','Travel','Community','Hobbies','Communication'],8:['Natural disasters','Science','Technology','Life','Culture','Environment'],9:['Grammar','Reading','Vocabulary','Communication','Sentence transformation'],10:['Grammar','Reading','Vocabulary','Communication','Environment'],11:['Reading','Grammar','Vocabulary','Critical thinking','Communication'],12:['Exam grammar','Reading','Vocabulary','Translation','Communication']};
const VERBS=[['play','plays','played'],['watch','watches','watched'],['study','studies','studied'],['wash','washes','washed'],['visit','visits','visited'],['carry','carries','carried'],['go','goes','went'],['have','has','had'],['do','does','did'],['try','tries','tried']];
const NOUNS=['football','English','books','music','chess','the piano','cartoons','computer games','science','breakfast'];
const WORDS=[['library','thư viện'],['bakery','tiệm bánh'],['forest','khu rừng'],['helmet','mũ bảo hiểm'],['journey','hành trình'],['healthy','khỏe mạnh'],['pollution','ô nhiễm'],['recycle','tái chế'],['festival','lễ hội'],['neighbor','hàng xóm'],['community','cộng đồng'],['protect','bảo vệ'],['dangerous','nguy hiểm'],['culture','văn hóa'],['technology','công nghệ'],['environment','môi trường'],['adventure','cuộc phiêu lưu'],['equipment','thiết bị'],['achievement','thành tích'],['knowledge','kiến thức']];
function makeQuestion(id,grade,topic,skill,difficulty,type,question,options,answer,explanation){return {id,grade,world:WORLDS[grade],topic,skill,difficulty,type,question,options,correctAnswer:answer,explanation};}
function buildQuestionBank(){const bank=[];for(const grade of [6,7,8,9,10,11,12]){for(let i=0;i<500;i++){const topic=TOPICS[grade][i%TOPICS[grade].length],difficulty=Math.min(5,1+Math.floor(i/100)),id=`g${grade}-${String(i+1).padStart(3,'0')}`,v=i%6;if(v===0){const x=VERBS[i%VERBS.length],plural=i%2===0,subject=plural?'They':(i%3?'He':'She'),answer=plural?x[0]:x[1];bank.push(makeQuestion(id,grade,topic,'Grammar',difficulty,'multiple_choice',`${subject} ___ ${NOUNS[i%NOUNS.length]} every day.`,[answer,plural?x[1]:x[0],x[2],'going'],answer,plural?'They dùng động từ nguyên mẫu.':'He/She/It dùng V(s/es).'));}else if(v===1){const x=WORDS[i%WORDS.length];bank.push(makeQuestion(id,grade,topic,'Vocabulary',difficulty,'multiple_choice',`Which word means “${x[1]}”?`,[x[0],'garden','window','station'],x[0],`${x[0]} = ${x[1]}.`));}else if(v===2){const x=VERBS[(i*3)%VERBS.length];bank.push(makeQuestion(id,grade,topic,'Grammar',difficulty,'fill_in_blank',`Yesterday, I ___ ${NOUNS[(i+2)%NOUNS.length]}.`,[],x[2],`Yesterday signals past simple: use ${x[2]}.`));}else if(v===3){const x=VERBS[(i+4)%VERBS.length],n=NOUNS[i%NOUNS.length];bank.push(makeQuestion(id,grade,topic,'Sentence arrangement',difficulty,'word_arrangement',`Arrange: ${x[0]} / ${n} / I`,[],`I ${x[0]} ${n}.`,'Word order: Subject + Verb + Object.'));}else if(v===4){const x=WORDS[(i*2)%WORDS.length];bank.push(makeQuestion(id,grade,topic,'Vocabulary',difficulty,'matching',`Match “${x[0]}” with its meaning.`,[x[1],'bạn bè','môi trường','trường học'],x[1],`${x[0]} means ${x[1]}.`));}else{const x=VERBS[(i+5)%VERBS.length],answer=x[1];bank.push(makeQuestion(id,grade,topic,'Grammar',difficulty,'multiple_choice',`My sister ___ ${NOUNS[i%NOUNS.length]} on Sundays.`,[answer,x[0],x[2],'going'],answer,'My sister is third-person singular, so use V(s/es).'));}}}return bank;}
const ENGLISH_QUESTIONS=buildQuestionBank();
if(typeof window!=='undefined')window.ENGLISH_QUESTIONS=ENGLISH_QUESTIONS;
if(typeof module!=='undefined')module.exports={ENGLISH_QUESTIONS,buildQuestionBank};
